# Generated by Django 4.2.28 on 2026-02-06 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_answered", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="learning.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="CardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ease", models.FloatField(default=2.5)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("wrong_streak", models.PositiveIntegerField(default=0)),
                ("correct_streak", models.PositiveIntegerField(default=0)),
                ("total_correct", models.PositiveIntegerField(default=0)),
                ("total_wrong", models.PositiveIntegerField(default=0)),
                ("last_answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="learning.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cardprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "card"), name="uniq_user_card_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="cardprogress",
            index=models.Index(
                fields=["user", "due_at"], name="learning_ca_user_id_7f0c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardprogress",
            index=models.Index(
                fields=["user", "card"], name="learning_ca_user_id_2e7b1f_idx"
            ),
        ),
    ]
