# Generated by Django 4.2.28 on 2026-02-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_difficulty_score'),
        ('learning', '0003_rename_learning_ca_user_id_7f0c9a_idx_learning_ca_user_id_a61012_idx_and_more'),
    ]

    operations = [
    ]
