# Generated by Django 4.2.28 on 2026-02-07 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0005_add_study_answer"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cardprogress",
            new_name="learning_ca_user_id_a61012_idx",
            old_name="learning_ca_user_id_7f0c9a_idx",
        ),
        migrations.RenameIndex(
            model_name="cardprogress",
            new_name="learning_ca_user_id_ce0e05_idx",
            old_name="learning_ca_user_id_2e7b1f_idx",
        ),
        migrations.RenameIndex(
            model_name="cardprogress",
            new_name="learning_ca_user_id_df3aa7_idx",
            old_name="learning_ca_user_id_diff_idx",
        ),
        migrations.RenameIndex(
            model_name="studyanswer",
            new_name="learning_st_session_b00a89_idx",
            old_name="learning_stu_session_8d7f58_idx",
        ),
        migrations.RenameIndex(
            model_name="studyanswer",
            new_name="learning_st_session_d5eb6f_idx",
            old_name="learning_stu_session_5a1f43_idx",
        ),
    ]
